/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geeks.foodieesoft.frames;

import geeks.foodieesoft.beans.FoodCategory;
import geeks.foodieesoft.beans.Permissions;
import geeks.foodieesoft.beans.UserType;
import geeks.foodieesoft.dao.DBManager;
import geeks.foodieesoft.dao.DBManagerInterface;
import static geeks.foodieesoft.frames.ProductPage.user_cat_id;
import geeks.foodieesoft.util.CurrentDate;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Vksoni
 */
public class FoodCategoryPage extends javax.swing.JFrame {

    /**
     * Creates new form UserType
     */
    DBManagerInterface dbManager;
    DefaultTableModel tableModelUserType;
    ArrayList<FoodCategory> food_category_list;
    public static int user_id = LoginPage.user_id;
    public static int user_cat_id = LoginPage.user_cat_id;

    public FoodCategoryPage() {
        initComponents();
        dbManager = new DBManager();
        tableModelUserType = (DefaultTableModel) this.jTableFoodCategory.getModel();
        showInTable();
        this.jButtonUpdate.setVisible(false);
        this.jButtonDelete.setVisible(false);
        
        
        
        JTableHeader header = this.jTableFoodCategory.getTableHeader();
        header.setBackground(new Color(0, 0, 51));
        header.setForeground(new Color(0, 204, 0));
        header.setFont(new Font("SansSerif", Font.BOLD, 16));

        this.jButtonSave.setEnabled(false);
        this.jButtonUpdate.setEnabled(false);
        this.jButtonDelete.setEnabled(false);
        checkPermissions(user_cat_id);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFoodCategory = new javax.swing.JTable();
        jTextFieldFoodName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jLabelMin = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDelete.setBackground(new java.awt.Color(0, 240, 0));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(0, 0, 51));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/delete.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.setBorder(null);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 260, 40));

        jTableFoodCategory.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableFoodCategory.setForeground(new java.awt.Color(0, 0, 51));
        jTableFoodCategory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Category"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFoodCategory.setGridColor(new java.awt.Color(0, 0, 51));
        jTableFoodCategory.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableFoodCategory.setSelectionForeground(new java.awt.Color(0, 240, 0));
        jTableFoodCategory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableFoodCategoryMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableFoodCategory);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 330, 360));

        jTextFieldFoodName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFoodName.setText("Enter Food Name");
        jTextFieldFoodName.setBorder(null);
        jTextFieldFoodName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldFoodName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldFoodNameMouseClicked(evt);
            }
        });
        jTextFieldFoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFoodNameActionPerformed(evt);
            }
        });
        jTextFieldFoodName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFoodNameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("Food Name*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 240, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        jButtonSave.setBackground(new java.awt.Color(0, 240, 0));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(0, 0, 51));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/save.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.setBorder(null);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 260, 40));

        jButtonUpdate.setBackground(new java.awt.Color(0, 240, 0));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(0, 0, 51));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/update.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setBorder(null);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 260, 40));

        jButtonClear.setBackground(new java.awt.Color(0, 240, 0));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(0, 0, 51));
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/clear.png"))); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.setBorder(null);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 33, 670, 380));

        jLabelMin.setBackground(new java.awt.Color(255, 0, 0));
        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 40, 40));

        jLabelExit.setBackground(new java.awt.Color(0, 0, 51));
        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelExit.setOpaque(true);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 40, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Food Categories");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int food_cat_id = food_category_list.get(this.jTableFoodCategory.getSelectedRow()).getFood_cat_id();
        int i = dbManager.removeFoodCategory(new FoodCategory(food_cat_id, 0, 0, 0, "", "", ""));

        if (i != 0) {
            JOptionPane.showMessageDialog(this, "Deleted Sucessfully");
            this.jTextFieldFoodName.setText("Enter Food Name");
            this.jButtonUpdate.setVisible(false);
            this.jButtonDelete.setVisible(false);
            this.jButtonSave.setVisible(true);

            showInTable();

}    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jTextFieldFoodNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFoodNameMouseClicked
        if (this.jTextFieldFoodName.getText().equalsIgnoreCase("Enter Food Name")) {
            this.jTextFieldFoodName.setText("");
        }
    }//GEN-LAST:event_jTextFieldFoodNameMouseClicked

    private void jTextFieldFoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFoodNameActionPerformed

    private void jTextFieldFoodNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFoodNameKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldFoodName.getText().equalsIgnoreCase("Enter Food Name")) {
            this.jTextFieldFoodName.setText("");
        }
    }//GEN-LAST:event_jTextFieldFoodNameKeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new HomePage(user_id, user_cat_id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        if (!(this.jTextFieldFoodName.getText().equals("Enter Food Name") || this.jTextFieldFoodName.getText().equals(""))) {

            int status = dbManager.saveFoodCategory(new FoodCategory(user_id, CurrentDate.getCurrentDate(), this.jTextFieldFoodName.getText()));
            showInTable();
            this.jTextFieldFoodName.setText("Enter Food Name");
            if (status != 0) {
                JOptionPane.showMessageDialog(this, "Successfully added");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill required field");
            this.jTextFieldFoodName.setText("Enter Food Name");

        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:

        int food_cat_id = food_category_list.get(this.jTableFoodCategory.getSelectedRow()).getFood_cat_id();
        int i = dbManager.modifyFoodCategory(new FoodCategory(food_cat_id, 0, 0, user_id, "", CurrentDate.getCurrentDate(),
                this.jTextFieldFoodName.getText()));

        if (i != 0) {
            JOptionPane.showMessageDialog(this, "Updated Sucessfully");
            this.jTextFieldFoodName.setText("Enter Food Name");
            this.jButtonUpdate.setVisible(false);
            this.jButtonDelete.setVisible(false);
            this.jButtonSave.setVisible(true);

            showInTable();

        }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        this.jTextFieldFoodName.setText("Enter Food Name");

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTableFoodCategoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableFoodCategoryMouseClicked
        // TODO add your handling code here:
        this.jButtonUpdate.setVisible(true);
        this.jButtonDelete.setVisible(true);
        this.jButtonSave.setVisible(false);

        this.jTextFieldFoodName.setText(food_category_list.get(this.jTableFoodCategory.getSelectedRow()).getFood_type());


    }//GEN-LAST:event_jTableFoodCategoryMouseClicked

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        // TODO add your handling code here:

        this.jLabelExit.setBackground(Color.red);
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        // TODO add your handling code here:
        this.jLabelExit.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_jLabelExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FoodCategoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FoodCategoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FoodCategoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FoodCategoryPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FoodCategoryPage().setVisible(true);
            }
        });
    }

    public void showInTable() {
        tableModelUserType.setRowCount(0);

        food_category_list = dbManager.getAllFoodTypes();
        for (FoodCategory foodCategory : food_category_list) {
            Vector V = new Vector();
            V.add(foodCategory.getFood_type());
            tableModelUserType.addRow(V);
        }
    }
    
        public void checkPermissions(int user_cat_id) {
        ArrayList<Permissions> permissions_name_list;
        permissions_name_list = dbManager.getUserPermissionName(user_cat_id);

        for (Permissions permissions : permissions_name_list) {
            if ((permissions.getPermission_name().equalsIgnoreCase("Add Food Category"))) {
                this.jButtonSave.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("Update Food Category"))) {
                this.jButtonUpdate.setEnabled(true);

            } else if ((permissions.getPermission_name().equalsIgnoreCase("Delete Food Category"))) {
                this.jButtonDelete.setEnabled(true);

            }

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableFoodCategory;
    private javax.swing.JTextField jTextFieldFoodName;
    // End of variables declaration//GEN-END:variables
}
