/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geeks.foodieesoft.frames;

import geeks.foodieesoft.beans.Permissions;
import geeks.foodieesoft.dao.DBManager;
import geeks.foodieesoft.dao.DBManagerInterface;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Vksoni
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form HomePage
     */
    public static int user_id;
    public static int user_cat_id;
    DBManagerInterface dbManager;

    public HomePage(int user_id, int user_cat_id) {
        initComponents();
        dbManager = new DBManager();
        this.jLabelUsename.setText(dbManager.retriveUsername(user_id));
        this.jButtonUser.setEnabled(false);
        this.jButtonCustomer.setEnabled(false);
        this.jButtonUserType.setEnabled(false);
        this.jButtonCatagorey.setEnabled(false);
        this.jButtonQuestion.setEnabled(false);
        this.jButtonOrder.setEnabled(false);
        this.jButtonProduct.setEnabled(false);
        checkPermissions(user_cat_id);

        if (!(dbManager.getUserType(user_cat_id).equalsIgnoreCase("Admin"))) {
            this.jButtonPermissions.setVisible(false);
        }
    }

    public HomePage() {
        initComponents();
        dbManager = new DBManager();
        checkPermissions(user_cat_id);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHomePage = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelUsename = new javax.swing.JLabel();
        jButtonUserType = new javax.swing.JButton();
        jButtonUser = new javax.swing.JButton();
        jButtonCatagorey = new javax.swing.JButton();
        jButtonCustomer = new javax.swing.JButton();
        jButtonQuestion = new javax.swing.JButton();
        jButtonPermissions = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButtonProduct = new javax.swing.JButton();
        jButtonOrder = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButtonOrder2 = new javax.swing.JButton();
        jLabelMin = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelHomePage.setBackground(new java.awt.Color(255, 255, 255));
        jPanelHomePage.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanelHomePage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelHomePage.setMinimumSize(new java.awt.Dimension(750, 450));
        jPanelHomePage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/profile.png"))); // NOI18N
        jPanelHomePage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/icons8_Exit_20px_1.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanelHomePage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 40, 20, 30));

        jLabelUsename.setBackground(new java.awt.Color(0, 0, 51));
        jLabelUsename.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUsename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelUsename.setText("Username");
        jPanelHomePage.add(jLabelUsename, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 70, 170, -1));

        jButtonUserType.setBackground(new java.awt.Color(0, 204, 0));
        jButtonUserType.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUserType.setForeground(new java.awt.Color(0, 0, 51));
        jButtonUserType.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/feature-5.png"))); // NOI18N
        jButtonUserType.setText("USER TYPE");
        jButtonUserType.setBorder(null);
        jButtonUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserTypeActionPerformed(evt);
            }
        });
        jPanelHomePage.add(jButtonUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 360, 90));

        jButtonUser.setBackground(new java.awt.Color(0, 204, 0));
        jButtonUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUser.setForeground(new java.awt.Color(0, 0, 51));
        jButtonUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/administrator-icon-5154.png"))); // NOI18N
        jButtonUser.setText("USER");
        jButtonUser.setBorder(null);
        jButtonUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUserActionPerformed(evt);
            }
        });
        jPanelHomePage.add(jButtonUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 360, 90));

        jButtonCatagorey.setBackground(new java.awt.Color(0, 204, 0));
        jButtonCatagorey.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCatagorey.setForeground(new java.awt.Color(0, 0, 51));
        jButtonCatagorey.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/2Restoran.png"))); // NOI18N
        jButtonCatagorey.setText("FOOD CATEGORY");
        jButtonCatagorey.setBorder(null);
        jButtonCatagorey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCatagoreyActionPerformed(evt);
            }
        });
        jPanelHomePage.add(jButtonCatagorey, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 360, 90));

        jButtonCustomer.setBackground(new java.awt.Color(0, 204, 0));
        jButtonCustomer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCustomer.setForeground(new java.awt.Color(0, 0, 51));
        jButtonCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/user-male-3.png"))); // NOI18N
        jButtonCustomer.setText("CUSTOMER");
        jButtonCustomer.setBorder(null);
        jButtonCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCustomerActionPerformed(evt);
            }
        });
        jPanelHomePage.add(jButtonCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 360, 90));

        jButtonQuestion.setBackground(new java.awt.Color(0, 204, 0));
        jButtonQuestion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonQuestion.setForeground(new java.awt.Color(0, 0, 51));
        jButtonQuestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Artboard_15-512 (1).png"))); // NOI18N
        jButtonQuestion.setText("QUESTIONS");
        jButtonQuestion.setBorder(null);
        jButtonQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQuestionActionPerformed(evt);
            }
        });
        jPanelHomePage.add(jButtonQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 300, 360, 90));

        jButtonPermissions.setBackground(new java.awt.Color(0, 204, 0));
        jButtonPermissions.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonPermissions.setForeground(new java.awt.Color(0, 0, 51));
        jButtonPermissions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/page-wise-permission.png"))); // NOI18N
        jButtonPermissions.setText("USER PERMISSIONS");
        jButtonPermissions.setBorder(null);
        jButtonPermissions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPermissionsActionPerformed(evt);
            }
        });
        jPanelHomePage.add(jButtonPermissions, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 360, 90));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Untitled-1.png"))); // NOI18N
        jPanelHomePage.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 180));

        jButtonProduct.setBackground(new java.awt.Color(0, 204, 0));
        jButtonProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonProduct.setForeground(new java.awt.Color(0, 0, 51));
        jButtonProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/144178-food-and-restaurant-set.png"))); // NOI18N
        jButtonProduct.setText("PRODUCTS");
        jButtonProduct.setBorder(null);
        jButtonProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProductActionPerformed(evt);
            }
        });
        jPanelHomePage.add(jButtonProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 360, 90));

        jButtonOrder.setBackground(new java.awt.Color(0, 204, 0));
        jButtonOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOrder.setForeground(new java.awt.Color(0, 0, 51));
        jButtonOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Success-Place-Order-Complete-Shopping-Tick-512.png"))); // NOI18N
        jButtonOrder.setText("Sale");
        jButtonOrder.setBorder(null);
        jButtonOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrderActionPerformed(evt);
            }
        });
        jPanelHomePage.add(jButtonOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 360, 90));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Welcome");
        jPanelHomePage.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        jButtonOrder2.setBackground(new java.awt.Color(0, 204, 0));
        jButtonOrder2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonOrder2.setForeground(new java.awt.Color(0, 0, 51));
        jButtonOrder2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/Check-512.png"))); // NOI18N
        jButtonOrder2.setText("Order Detail");
        jButtonOrder2.setBorder(null);
        jButtonOrder2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOrder2ActionPerformed(evt);
            }
        });
        jPanelHomePage.add(jButtonOrder2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 360, 90));

        getContentPane().add(jPanelHomePage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 1180, 550));

        jLabelMin.setBackground(new java.awt.Color(255, 0, 0));
        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 0, 40, 40));

        jLabelExit.setBackground(new java.awt.Color(0, 0, 51));
        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelExit.setOpaque(true);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 40, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Home Page");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 40));

        jLabel7.setBackground(new java.awt.Color(0, 204, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Geeks Academy|All Right Reserved");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 1180, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPermissionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPermissionsActionPerformed
        // TODO add your handling code here:
        new UserPermissionsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonPermissionsActionPerformed

    private void jButtonQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQuestionActionPerformed
        // TODO add your handling code here:
        new QuestionsPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonQuestionActionPerformed

    private void jButtonCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomerActionPerformed
        // TODO add your handling code here:
        new CustomerPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCustomerActionPerformed

    private void jButtonCatagoreyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCatagoreyActionPerformed
        new FoodCategoryPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCatagoreyActionPerformed

    private void jButtonUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserTypeActionPerformed
        new UserTypePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonUserTypeActionPerformed

    private void jButtonProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProductActionPerformed

        // TODO add your handling code here:
        new ProductPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonProductActionPerformed

    private void jButtonOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrderActionPerformed
        // TODO add your handling code here:
        new SalePage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonOrderActionPerformed

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        // TODO add your handling code here:
        this.jLabelExit.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        // TODO add your handling code here:

        this.jLabelExit.setBackground(Color.red);
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jButtonUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUserActionPerformed
        // TODO add your handling code here:
        new UserPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonUserActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButtonOrder2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOrder2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new OrderDetailPage().setVisible(true);
    }//GEN-LAST:event_jButtonOrder2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    public void checkPermissions(int user_cat_id) {
        ArrayList<Permissions> permissions_name_list;
        permissions_name_list = dbManager.getUserPermissionName(user_cat_id);

        for (Permissions permissions : permissions_name_list) {
            if ((permissions.getPermission_name().equalsIgnoreCase("View User"))) {
                this.jButtonUser.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Customer"))) {
                this.jButtonCustomer.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View User Type"))) {
                this.jButtonUserType.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Food Category"))) {
                this.jButtonCatagorey.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Question"))) {
                this.jButtonQuestion.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Order"))) {
                this.jButtonOrder.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("View Product"))) {
                this.jButtonProduct.setEnabled(true);
            }
        }
        

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCatagorey;
    private javax.swing.JButton jButtonCustomer;
    private javax.swing.JButton jButtonOrder;
    private javax.swing.JButton jButtonOrder2;
    private javax.swing.JButton jButtonPermissions;
    private javax.swing.JButton jButtonProduct;
    private javax.swing.JButton jButtonQuestion;
    private javax.swing.JButton jButtonUser;
    private javax.swing.JButton jButtonUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelUsename;
    private javax.swing.JPanel jPanelHomePage;
    // End of variables declaration//GEN-END:variables
}
