/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geeks.foodieesoft.frames;

import geeks.foodieesoft.beans.FoodCategory;
import geeks.foodieesoft.beans.Order;
import geeks.foodieesoft.beans.OrderDetail;
import geeks.foodieesoft.beans.Product;
import geeks.foodieesoft.dao.DBManager;
import geeks.foodieesoft.dao.DBManagerInterface;
import java.awt.Color;
import java.awt.Font;
import java.text.SimpleDateFormat;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vksoni
 */
public class OrderDetailPage extends javax.swing.JFrame {

    DBManagerInterface dbManager;
    DefaultTableModel tableModelOrder;
    DefaultTableModel tableModelOrderDetail;
    TableRowSorter<DefaultTableModel> rowSorter = null;

    ArrayList<Order> order_list;
    ArrayList<Order> order_list_between_dates;

    ArrayList<OrderDetail> order_detail_list;

    public static int user_id = LoginPage.user_id;
    public static int user_cat_id = LoginPage.user_cat_id;

    public OrderDetailPage() {
        initComponents();
        dbManager = new DBManager();
        tableModelOrder = (DefaultTableModel) this.jTableOrder.getModel();
        tableModelOrderDetail = (DefaultTableModel) this.jTableOrderDetail.getModel();
        this.jXDatePickerTo.setFormats("yyyy/MM/dd");
        this.jXDatePickerFrom.setFormats("yyyy/MM/dd");
        rowSorter = new TableRowSorter<DefaultTableModel>(tableModelOrder);
        this.jTableOrder.setRowSorter(rowSorter);

        showInTable();

        JTableHeader header = this.jTableOrderDetail.getTableHeader();
        header.setBackground(new Color(0, 0, 51));
        header.setForeground(new Color(0, 204, 0));
        header.setFont(new Font("SansSerif", Font.BOLD, 16));

        JTableHeader headerOrderDetail = this.jTableOrder.getTableHeader();
        headerOrderDetail.setBackground(new Color(0, 0, 51));
        headerOrderDetail.setForeground(new Color(0, 204, 0));
        headerOrderDetail.setFont(new Font("SansSerif", Font.BOLD, 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelMin = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrderDetail = new javax.swing.JTable();
        jButtonSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        jXDatePickerFrom = new org.jdesktop.swingx.JXDatePicker();
        jXDatePickerTo = new org.jdesktop.swingx.JXDatePicker();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jTextFieldSerachProducts = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMin.setBackground(new java.awt.Color(255, 0, 0));
        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 0, 40, 40));

        jLabelExit.setBackground(new java.awt.Color(0, 0, 51));
        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelExit.setOpaque(true);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 0, 40, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Order Detail");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableOrderDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableOrderDetail.setForeground(new java.awt.Color(0, 0, 51));
        jTableOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item Quantity", "Individual Total "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOrderDetail.setToolTipText("Products");
        jTableOrderDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableOrderDetail.setGridColor(new java.awt.Color(0, 0, 51));
        jTableOrderDetail.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableOrderDetail.setSelectionForeground(new java.awt.Color(0, 240, 0));
        jTableOrderDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOrderDetailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableOrderDetail);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 160, 350, 380));

        jButtonSearch.setBackground(new java.awt.Color(0, 204, 0));
        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(0, 0, 51));
        jButtonSearch.setText("Search");
        jButtonSearch.setBorder(null);
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 240, 30));

        jTableOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableOrder.setForeground(new java.awt.Color(0, 0, 51));
        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Id", "Bill Number", "Customer name", "Purchase Date", "Discount", "Total Bill (Rs)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableOrder.setToolTipText("Products");
        jTableOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableOrder.setGridColor(new java.awt.Color(0, 0, 51));
        jTableOrder.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableOrder.setSelectionForeground(new java.awt.Color(0, 240, 0));
        jTableOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableOrderMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableOrder);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 870, 380));

        jXDatePickerFrom.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jXDatePickerFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 180, 30));

        jXDatePickerTo.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.add(jXDatePickerTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 180, 30));

        jLabel6.setBackground(new java.awt.Color(0, 204, 0));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Sales History Details");
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("To");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 30, -1));

        jButtonBack.setBackground(new java.awt.Color(0, 204, 0));
        jButtonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(0, 0, 51));
        jButtonBack.setText("Back");
        jButtonBack.setBorder(null);
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("From");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 204, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 51));
        jLabel9.setText("Sales History");
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 40, 260, -1));

        jTextFieldSerachProducts.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldSerachProducts.setText("search products ....");
        jTextFieldSerachProducts.setBorder(null);
        jTextFieldSerachProducts.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldSerachProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSerachProductsMouseClicked(evt);
            }
        });
        jTextFieldSerachProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSerachProductsActionPerformed(evt);
            }
        });
        jTextFieldSerachProducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSerachProductsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSerachProductsKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldSerachProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 20, 260, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 51));
        jLabel13.setText("SEARCH:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1280, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        // TODO add your handling code here:

        this.jLabelExit.setBackground(Color.red);
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        // TODO add your handling code here:
        this.jLabelExit.setBackground(new Color(0, 0, 51));
    }//GEN-LAST:event_jLabelExitMouseExited

    private void jTableOrderDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrderDetailMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jTableOrderDetailMouseClicked

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
        String fromDate = new SimpleDateFormat("yyyy/MM/dd").format(this.jXDatePickerFrom.getDate());
        String toDate = new SimpleDateFormat("yyyy/MM/dd").format(this.jXDatePickerTo.getDate());
//
        // System.out.println(fromDate + "   " + toDate);
        showInTableOrderBetweenDates(fromDate, toDate);


    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTableOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableOrderMouseClicked
        // TODO add your handling code here:
        int order_id = (int) this.jTableOrder.getValueAt(this.jTableOrder.getSelectedRow(), 0);
        System.out.println(order_id);
        showInOrderDetailTable(order_id);

    }//GEN-LAST:event_jTableOrderMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        new HomePage(user_id, user_cat_id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jTextFieldSerachProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsMouseClicked
        if (this.jTextFieldSerachProducts.getText().equalsIgnoreCase("search products ....")) {
            this.jTextFieldSerachProducts.setText("");
        }
    }//GEN-LAST:event_jTextFieldSerachProductsMouseClicked

    private void jTextFieldSerachProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSerachProductsActionPerformed

    private void jTextFieldSerachProductsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsKeyPressed
        if (this.jTextFieldSerachProducts.getText().equalsIgnoreCase("search products ....")) {
            this.jTextFieldSerachProducts.setText("");
        }
    }//GEN-LAST:event_jTextFieldSerachProductsKeyPressed

    private void jTextFieldSerachProductsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSerachProductsKeyReleased
        // TODO add your handling code here:

        String searchData = this.jTextFieldSerachProducts.getText();
        rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchData));
    }//GEN-LAST:event_jTextFieldSerachProductsKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetailPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetailPage().setVisible(true);
            }
        });
    }

    public void showInTable() {
        tableModelOrder.setRowCount(0);

        order_list = dbManager.getAllOrder();
        for (Order order : order_list) {
            Vector V = new Vector();
            V.add(order.getOrder_id());
            V.add(order.getNumber());
            V.add(dbManager.getCustomerDetail(order.getCustomer_id()).getCustomer_name());
            V.add(order.getCreated_date());
            V.add(dbManager.getDiscountTypeById(order.getDiscount_id()).getDiscount_type() + ": " + order.getDiscount());
            V.add(order.getTotal_bill());

            tableModelOrder.addRow(V);
        }
    }

    public void showInOrderDetailTable(int order_id) {
        tableModelOrderDetail.setRowCount(0);

        order_detail_list = dbManager.getAllOrderDetailById(order_id);
        for (OrderDetail order : order_detail_list) {
            Vector V = new Vector();
            V.add(dbManager.getProduct(order.getProduct_id()).getFood_name());
            V.add(order.getQantity());
            V.add(order.getTotal_price());

            tableModelOrderDetail.addRow(V);
        }
    }

    public void showInTableOrderBetweenDates(String from, String to) {
        tableModelOrder.setRowCount(0);

        order_list_between_dates = dbManager.getAllOrderBetweenDate(from, to);
        for (Order order : order_list_between_dates) {
            Vector V = new Vector();
            V.add(order.getOrder_id());
            V.add(order.getNumber());
            V.add(dbManager.getCustomerDetail(order.getCustomer_id()).getCustomer_name());
            V.add(order.getCreated_date());
            V.add(dbManager.getDiscountTypeById(order.getDiscount_id()).getDiscount_type() + ": " + order.getDiscount());
            V.add(order.getTotal_bill());

            tableModelOrder.addRow(V);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTable jTableOrderDetail;
    private javax.swing.JTextField jTextFieldSerachProducts;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerFrom;
    private org.jdesktop.swingx.JXDatePicker jXDatePickerTo;
    // End of variables declaration//GEN-END:variables
}
