/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geeks.foodieesoft.frames;

import geeks.foodieesoft.beans.FoodCategory;
import geeks.foodieesoft.beans.Permissions;
import geeks.foodieesoft.beans.Product;
import geeks.foodieesoft.dao.DBManager;
import geeks.foodieesoft.dao.DBManagerInterface;
import static geeks.foodieesoft.frames.CustomerPage.user_cat_id;
import geeks.foodieesoft.util.CurrentDate;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Vksoni
 */
public class ProductPage extends javax.swing.JFrame {

    /**
     * Creates new form UserType
     */
    DBManagerInterface dbManager;
    DefaultTableModel tableModelProduct;
    DefaultComboBoxModel comboBoxModelCategory;
    public ArrayList<Product> products_list;
    ArrayList<FoodCategory> category_list;

    public static int user_id = LoginPage.user_id;
    public static int user_cat_id = LoginPage.user_cat_id;

    public ProductPage() {
        initComponents();
        dbManager = new DBManager();
        tableModelProduct = (DefaultTableModel) this.jTableProduct.getModel();
        comboBoxModelCategory = (DefaultComboBoxModel) this.jComboBoxCategories.getModel();
        this.jComboBoxCategories.setVisible(true);
        category_list = dbManager.getAllFoodTypes();
        showInTable();
        showInComboBox();

        this.jButtonUpdate.setVisible(false);
        this.jButtonDelete.setVisible(false);

        JTableHeader header = this.jTableProduct.getTableHeader();
        header.setBackground(new Color(0, 0, 51));
        header.setForeground(new Color(0, 204, 0));
        header.setFont(new Font("SansSerif", Font.BOLD, 16));

        this.jButtonSave.setEnabled(false);
        this.jButtonUpdate.setEnabled(false);
        this.jButtonDelete.setEnabled(false);
        checkPermissions(user_cat_id);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldFoodName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldPrice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxCategories = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSpinnerQuantity = new javax.swing.JSpinner();
        jLabelMin = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDelete.setBackground(new java.awt.Color(0, 240, 0));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(0, 0, 51));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/delete.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.setBorder(null);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 260, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 51));
        jLabel5.setText("CATEGORY*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 240, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        jButtonSave.setBackground(new java.awt.Color(0, 240, 0));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(0, 0, 51));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/save.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.setBorder(null);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 260, 40));

        jButtonUpdate.setBackground(new java.awt.Color(0, 240, 0));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(0, 0, 51));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/update.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setBorder(null);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 260, 40));

        jButtonClear.setBackground(new java.awt.Color(0, 240, 0));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(0, 0, 51));
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/clear.png"))); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.setBorder(null);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 260, 40));

        jTableProduct.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableProduct.setForeground(new java.awt.Color(0, 0, 51));
        jTableProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Food Name", "Category", "Price", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableProduct.setToolTipText("Products");
        jTableProduct.setColumnSelectionAllowed(true);
        jTableProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableProduct.setGridColor(new java.awt.Color(0, 0, 51));
        jTableProduct.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableProduct.setSelectionForeground(new java.awt.Color(0, 240, 0));
        jTableProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableProduct);
        jTableProduct.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTableProduct.getColumnModel().getColumnCount() > 0) {
            jTableProduct.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTableProduct.getColumnModel().getColumn(3).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 770, 490));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, -1));

        jTextFieldFoodName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldFoodName.setText("Enter Food Name...");
        jTextFieldFoodName.setBorder(null);
        jTextFieldFoodName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldFoodName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldFoodNameMouseClicked(evt);
            }
        });
        jTextFieldFoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFoodNameActionPerformed(evt);
            }
        });
        jTextFieldFoodName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFoodNameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("FOOD NAME*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 260, -1));

        jTextFieldPrice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldPrice.setText("Enter Price...");
        jTextFieldPrice.setBorder(null);
        jTextFieldPrice.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPriceMouseClicked(evt);
            }
        });
        jTextFieldPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPriceActionPerformed(evt);
            }
        });
        jTextFieldPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPriceKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 260, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 51));
        jLabel7.setText("PRICE*");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jComboBoxCategories.setBackground(new java.awt.Color(0, 0, 51));
        jComboBoxCategories.setForeground(new java.awt.Color(0, 240, 0));
        jComboBoxCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriesActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 51));
        jLabel8.setText("QUNATITY");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jSpinnerQuantity.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 1, true));
        jPanel1.add(jSpinnerQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 130, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1090, 540));

        jLabelMin.setBackground(new java.awt.Color(255, 0, 0));
        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jLabelMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelMinKeyPressed(evt);
            }
        });
        getContentPane().add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 40, 40));

        jLabelExit.setBackground(new java.awt.Color(0, 0, 51));
        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelExit.setOpaque(true);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, 40, 40));

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 204, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Products");
        jLabel9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int product_id = products_list.get(this.jTableProduct.getSelectedRow()).getProduct_id();
        int i = dbManager.removeProducts(new Product(product_id, 0, 0, 0, 0, 0, 0, "", "", ""));

        if (i != 0) {
            JOptionPane.showMessageDialog(this, "Deleted Sucessfully");
            this.jTextFieldFoodName.setText("Enter Food Name......");
            this.jTextFieldPrice.setText("Enter Price...");
            this.jButtonUpdate.setVisible(false);
            this.jButtonDelete.setVisible(false);
            this.jButtonSave.setVisible(true);
            this.jSpinnerQuantity.setValue(0);
            this.jComboBoxCategories.setSelectedIndex(0);

            showInTable();

}    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new HomePage(user_id, user_cat_id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        if (!((this.jTextFieldFoodName.getText().equals("Enter Food Name...") || this.jTextFieldPrice.getText().equals("Enter Price...") || this.jSpinnerQuantity.getValue().equals(0)
                || this.jTextFieldFoodName.getText().equals("") || this.jTextFieldPrice.getText().equals("")))) {

            int food_cat_id = category_list.get(this.jComboBoxCategories.getSelectedIndex()).getFood_cat_id();
            int price = Integer.parseInt(this.jTextFieldPrice.getText());
            int quantity = Integer.parseInt("" + this.jSpinnerQuantity.getValue());
            int status = dbManager.saveProducts(new Product(0, food_cat_id, 1, price,
                    quantity, user_id, 0, CurrentDate.getCurrentDate(), "", this.jTextFieldFoodName.getText()));

            if (status != 0) {
                JOptionPane.showMessageDialog(this, "Successfully added");
                showInTable();
                this.jTextFieldFoodName.setText("Enter Food Name...");
                this.jTextFieldPrice.setText("Enter Price...");
                this.jSpinnerQuantity.setValue(0);
                this.jComboBoxCategories.setSelectedIndex(0);

            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill required field");


    }//GEN-LAST:event_jButtonSaveActionPerformed
    }
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
//        
        int product_id = products_list.get(this.jTableProduct.getSelectedRow()).getProduct_id();
        int food_cat_id = category_list.get(this.jComboBoxCategories.getSelectedIndex()).getFood_cat_id();

        int price = products_list.get(this.jTableProduct.getSelectedRow()).getPrice();
        int quantity = products_list.get(this.jTableProduct.getSelectedRow()).getQuantity();
        String food_name = products_list.get(this.jTableProduct.getSelectedRow()).getFood_name();

        int i = dbManager.modifyProducts(new Product(product_id, food_cat_id, 0, price, quantity, 0, user_id, "", CurrentDate.getCurrentDate(),
                this.jTextFieldFoodName.getText()));

        if (i != 0) {
            JOptionPane.showMessageDialog(this, "Updated Sucessfully");
            this.jTextFieldFoodName.setText("Enter Food Name...");
            this.jTextFieldPrice.setText("Enter Price...");
            this.jSpinnerQuantity.setValue(0);
            this.jButtonUpdate.setVisible(false);
            this.jButtonDelete.setVisible(false);
            this.jButtonSave.setVisible(true);
            this.jComboBoxCategories.setSelectedIndex(0);
            showInTable();

        }

    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        this.jTextFieldFoodName.setText("Enter Food Name...");
        this.jTextFieldPrice.setText("Enter Price...");
        this.jSpinnerQuantity.setValue(0);

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTableProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableProductMouseClicked
        // TODO add your handling code here:
        int food_cat_id = products_list.get(this.jTableProduct.getSelectedRow()).getFood_cat_id();
        this.jButtonUpdate.setVisible(true);
        this.jButtonDelete.setVisible(true);
        this.jButtonSave.setVisible(false);
        this.jTextFieldFoodName.setText(products_list.get(this.jTableProduct.getSelectedRow()).getFood_name());
        this.jTextFieldPrice.setText("" + products_list.get(this.jTableProduct.getSelectedRow()).getPrice());
        this.jSpinnerQuantity.setValue(Integer.parseInt("" + products_list.get(this.jTableProduct.getSelectedRow()).getQuantity()));
        this.jComboBoxCategories.setSelectedItem(dbManager.getFoodType(food_cat_id));
    }//GEN-LAST:event_jTableProductMouseClicked

    private void jTextFieldFoodNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldFoodNameMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldFoodName.getText().equalsIgnoreCase("Enter Food Name...")) {
            this.jTextFieldFoodName.setText("");
        }
    }//GEN-LAST:event_jTextFieldFoodNameMouseClicked

    private void jTextFieldFoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFoodNameActionPerformed

    private void jTextFieldFoodNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFoodNameKeyPressed
        if (this.jTextFieldFoodName.getText().equalsIgnoreCase("Enter Food Name...")) {
            this.jTextFieldFoodName.setText("");
        }
    }//GEN-LAST:event_jTextFieldFoodNameKeyPressed

    private void jTextFieldPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPriceMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldPrice.getText().equalsIgnoreCase("Enter Price...")) {
            this.jTextFieldPrice.setText("");
        }
    }//GEN-LAST:event_jTextFieldPriceMouseClicked

    private void jTextFieldPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPriceActionPerformed

    private void jTextFieldPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPriceKeyPressed

        if (this.jTextFieldPrice.getText().equalsIgnoreCase("Enter Price...")) {
            this.jTextFieldPrice.setText("");
        }
    }//GEN-LAST:event_jTextFieldPriceKeyPressed

    private void jComboBoxCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCategoriesActionPerformed

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelMinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelMinKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMinKeyPressed

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        this.jLabelExit.setBackground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        this.jLabelExit.setBackground(new Color(0, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductPage().setVisible(true);
            }
        });
    }

    public void showInComboBox() {
        category_list = dbManager.getAllFoodTypes();
        for (FoodCategory foodCategory : category_list) {

            this.jComboBoxCategories.addItem("" + foodCategory.getFood_type());

        }
    }

    public void showInTable() {
        tableModelProduct.setRowCount(0);

        products_list = dbManager.getAllProducts();
        for (Product product : products_list) {
            Vector V = new Vector();
            V.add(product.getFood_name());
            V.add(dbManager.getFoodType(product.getFood_cat_id()));
            V.add(product.getPrice());
            V.add(product.getQuantity());

            tableModelProduct.addRow(V);
        }
    }

    public void checkPermissions(int user_cat_id) {
        ArrayList<Permissions> permissions_name_list;
        permissions_name_list = dbManager.getUserPermissionName(user_cat_id);

        for (Permissions permissions : permissions_name_list) {
            if ((permissions.getPermission_name().equalsIgnoreCase("Add Product"))) {
                this.jButtonSave.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("Update Product"))) {
                this.jButtonUpdate.setEnabled(true);

            } else if ((permissions.getPermission_name().equalsIgnoreCase("Delete Product"))) {
                this.jButtonDelete.setEnabled(true);

            }

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxCategories;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSpinner jSpinnerQuantity;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTextField jTextFieldFoodName;
    private javax.swing.JTextField jTextFieldPrice;
    // End of variables declaration//GEN-END:variables
}
