/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geeks.foodieesoft.frames;

import geeks.foodieesoft.beans.Customer;
import geeks.foodieesoft.beans.Permissions;
import geeks.foodieesoft.beans.Questions;
import geeks.foodieesoft.beans.User;
import geeks.foodieesoft.beans.UserType;
import geeks.foodieesoft.dao.DBManager;
import geeks.foodieesoft.dao.DBManagerInterface;
import geeks.foodieesoft.util.CurrentDate;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Vksoni
 */
public class UserPage extends javax.swing.JFrame {

    /**
     * Creates new form UserType
     */
    DBManagerInterface dbManager;
    DefaultTableModel tableModelCustomer;
    DefaultComboBoxModel comboBoxModelUserType;
    DefaultComboBoxModel comboBoxModelQuestions;
    public ArrayList<UserType> user_types_list;
    public ArrayList<Questions> questions_list;
    public ArrayList<User> users_list;

    public static int user_id = LoginPage.user_id;
    public static int user_cat_id = LoginPage.user_cat_id;

    public UserPage() {
        initComponents();
        dbManager = new DBManager();
        tableModelCustomer = (DefaultTableModel) this.jTableUser.getModel();
        comboBoxModelUserType = (DefaultComboBoxModel) this.jComboBoxUserType.getModel();
        this.jComboBoxUserType.setVisible(true);
        comboBoxModelQuestions = (DefaultComboBoxModel) this.jComboBoxQuestions.getModel();
        this.jComboBoxQuestions.setVisible(true);

        showInQuestionsComboBox();
        showInUserTypesComboBox();
        showInTable();

        this.jButtonUpdate.setVisible(false);
        this.jButtonDelete.setVisible(false);

        this.jButtonSave.setEnabled(false);
        this.jButtonUpdate.setEnabled(false);
        this.jButtonDelete.setEnabled(false);
        checkPermissions(user_cat_id);

        JTableHeader header = this.jTableUser.getTableHeader();
        header.setBackground(new Color(0, 0, 51));
        header.setForeground(new Color(0, 204, 0));
        header.setFont(new Font("SansSerif", Font.BOLD, 16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldUsername = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelRetype = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jTextFieldContact = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jTextFieldAddress = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jTextFieldAnswer = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jComboBoxQuestions = new javax.swing.JComboBox<>();
        jComboBoxUserType = new javax.swing.JComboBox<>();
        jTextFieldPassword = new javax.swing.JPasswordField();
        jTextFieldRetypePassword = new javax.swing.JPasswordField();
        jLabelMin = new javax.swing.JLabel();
        jLabelExit = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 51), 2, true));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonDelete.setBackground(new java.awt.Color(0, 204, 0));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(0, 0, 51));
        jButtonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/delete.png"))); // NOI18N
        jButtonDelete.setText("Delete");
        jButtonDelete.setBorder(null);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 260, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("USER TYPE*");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 51));
        jButton2.setText("Back");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        jButtonSave.setBackground(new java.awt.Color(0, 204, 0));
        jButtonSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonSave.setForeground(new java.awt.Color(0, 0, 51));
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/save.png"))); // NOI18N
        jButtonSave.setText("Save");
        jButtonSave.setBorder(null);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 260, 40));

        jButtonUpdate.setBackground(new java.awt.Color(0, 204, 0));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(0, 0, 51));
        jButtonUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/update.png"))); // NOI18N
        jButtonUpdate.setText("Update");
        jButtonUpdate.setBorder(null);
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, 260, 40));

        jButtonClear.setBackground(new java.awt.Color(0, 204, 0));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(0, 0, 51));
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geeks/foodieesoft/images/clear.png"))); // NOI18N
        jButtonClear.setText("Clear");
        jButtonClear.setBorder(null);
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 260, 40));

        jTableUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTableUser.setForeground(new java.awt.Color(0, 0, 51));
        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Type", "Username", "Name", "Contact#", "Address", "Question", "Answer"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUser.setToolTipText("Products");
        jTableUser.setColumnSelectionAllowed(true);
        jTableUser.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableUser.setGridColor(new java.awt.Color(0, 0, 51));
        jTableUser.setSelectionBackground(new java.awt.Color(0, 0, 51));
        jTableUser.setSelectionForeground(new java.awt.Color(0, 204, 0));
        jTableUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableUser);
        jTableUser.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (jTableUser.getColumnModel().getColumnCount() > 0) {
            jTableUser.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTableUser.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTableUser.getColumnModel().getColumn(2).setPreferredWidth(10);
            jTableUser.getColumnModel().getColumn(3).setPreferredWidth(15);
            jTableUser.getColumnModel().getColumn(4).setPreferredWidth(10);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 910, 430));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 260, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("USERNAME*");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jTextFieldUsername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldUsername.setText("Enter Username...");
        jTextFieldUsername.setBorder(null);
        jTextFieldUsername.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldUsernameMouseClicked(evt);
            }
        });
        jTextFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsernameActionPerformed(evt);
            }
        });
        jTextFieldUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsernameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 20));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 260, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("PASSWORD*");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 260, -1));

        jLabelRetype.setBackground(new java.awt.Color(0, 0, 51));
        jLabelRetype.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRetype.setText("RETYPE PASSWORD*");
        jPanel1.add(jLabelRetype, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 260, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("NAME*");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldName.setText("Enter Name..");
        jTextFieldName.setBorder(null);
        jTextFieldName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNameMouseClicked(evt);
            }
        });
        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });
        jTextFieldName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNameKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 260, 20));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 260, -1));

        jTextFieldContact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldContact.setText("Enter Contact...");
        jTextFieldContact.setBorder(null);
        jTextFieldContact.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldContact.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldContactMouseClicked(evt);
            }
        });
        jTextFieldContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldContactActionPerformed(evt);
            }
        });
        jTextFieldContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldContactKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 260, 20));

        jLabel10.setBackground(new java.awt.Color(0, 0, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("CONTACT");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, 20));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 260, -1));

        jLabel11.setBackground(new java.awt.Color(0, 0, 51));
        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("ADDRESS");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 260, -1));

        jTextFieldAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAddress.setText("Enter Address..");
        jTextFieldAddress.setBorder(null);
        jTextFieldAddress.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldAddressMouseClicked(evt);
            }
        });
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });
        jTextFieldAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAddressKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 260, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 51));
        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("QUESTION");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 260, -1));

        jTextFieldAnswer.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextFieldAnswer.setText("Enter Answer...");
        jTextFieldAnswer.setBorder(null);
        jTextFieldAnswer.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        jTextFieldAnswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldAnswerMouseClicked(evt);
            }
        });
        jTextFieldAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnswerActionPerformed(evt);
            }
        });
        jTextFieldAnswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldAnswerKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 260, 20));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("ANSWER");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, 20));

        jComboBoxQuestions.setBackground(new java.awt.Color(0, 0, 51));
        jComboBoxQuestions.setForeground(new java.awt.Color(0, 204, 0));
        jComboBoxQuestions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxQuestionsActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxQuestions, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 260, -1));

        jComboBoxUserType.setBackground(new java.awt.Color(0, 0, 51));
        jComboBoxUserType.setForeground(new java.awt.Color(0, 204, 0));
        jComboBoxUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUserTypeActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 260, -1));

        jTextFieldPassword.setText("Enter Password...");
        jTextFieldPassword.setBorder(null);
        jTextFieldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldPasswordMouseClicked(evt);
            }
        });
        jTextFieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPasswordActionPerformed(evt);
            }
        });
        jTextFieldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 260, -1));

        jTextFieldRetypePassword.setText("Retype Password...");
        jTextFieldRetypePassword.setBorder(null);
        jTextFieldRetypePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldRetypePasswordMouseClicked(evt);
            }
        });
        jTextFieldRetypePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRetypePasswordActionPerformed(evt);
            }
        });
        jTextFieldRetypePassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldRetypePasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldRetypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 260, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1220, 610));

        jLabelMin.setBackground(new java.awt.Color(255, 0, 0));
        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMin.setText("-");
        jLabelMin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });
        jLabelMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabelMinKeyPressed(evt);
            }
        });
        getContentPane().add(jLabelMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 40, 40));

        jLabelExit.setBackground(new java.awt.Color(0, 0, 51));
        jLabelExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExit.setText("X");
        jLabelExit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabelExit.setOpaque(true);
        jLabelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelExitMouseExited(evt);
            }
        });
        getContentPane().add(jLabelExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 0, 40, 40));

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("User ");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int users_id = users_list.get(this.jTableUser.getSelectedRow()).getUser_id();
        int i = dbManager.removeUser(new User(users_id, 0, 0, 0, 0, 0, "", "", "", "", "", "", "", ""));

        if (i != 0) {
            JOptionPane.showMessageDialog(this, "Deleted Sucessfully");
            this.jButtonUpdate.setVisible(false);
            this.jButtonDelete.setVisible(false);
            this.jButtonSave.setVisible(true);
            this.jTextFieldUsername.setText("Enter Username...");
            this.jTextFieldPassword.setText("Enter Password...");
            this.jTextFieldRetypePassword.setText("Retype Password...");
            this.jTextFieldContact.setText("Enter Contact..");
            this.jTextFieldAnswer.setText("Enter Answer...");
            this.jTextFieldAddress.setText("Enter Address...");
            this.jTextFieldName.setText("Enter Name..");
            this.jComboBoxUserType.setSelectedIndex(0);
            this.jComboBoxQuestions.setSelectedIndex(0);

            showInTable();

}    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new HomePage(user_id, user_cat_id).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        int user_cat_id = user_types_list.get(this.jComboBoxUserType.getSelectedIndex()).getUser_cat_id();
        int question_id = questions_list.get(this.jComboBoxQuestions.getSelectedIndex()).getQuestion_id();

        String username = this.jTextFieldUsername.getText();
        String password = this.jTextFieldPassword.getText();
        String reTypePassword = this.jTextFieldRetypePassword.getText();
        String name = this.jTextFieldName.getText();
        String contact = this.jTextFieldContact.getText();
        String address = this.jTextFieldAddress.getText();
        String answer = this.jTextFieldAnswer.getText();

        if (!(username.equalsIgnoreCase("Enter Username...") || password.equalsIgnoreCase("Enter Password...")
                || reTypePassword.equalsIgnoreCase("Retype Password...")
                || name.equalsIgnoreCase("Enter Name..") || username.equalsIgnoreCase("") || password.equalsIgnoreCase("")
                || reTypePassword.equalsIgnoreCase("")
                || name.equalsIgnoreCase("") || name.equalsIgnoreCase(""))) {

            if (contact.equalsIgnoreCase("Enter Contact...")) {
                contact = "";
            }
            if (answer.equalsIgnoreCase("Enter Answer...")) {
                answer = "";
            }
            if (address.equalsIgnoreCase("Enter Address..")) {
                address = "";
            }

            if (reTypePassword.equals(password)) {
                int status = dbManager.saveUsers(
                        new User(0, user_cat_id, question_id, 1, user_id, 0, username, password, name,
                                address, "", contact, answer, CurrentDate.getCurrentDate()));

                if (status != 0) {
                    JOptionPane.showMessageDialog(this, "Successfully added");
                    showInTable();
                    this.jTextFieldUsername.setText("Enter Username...");
                    this.jTextFieldPassword.setText("Enter Password...");
                    this.jTextFieldRetypePassword.setText("Retype Password...");
                    this.jTextFieldContact.setText("Enter Contact..");
                    this.jTextFieldAnswer.setText("Enter Answer...");
                    this.jTextFieldAddress.setText("Enter Address...");
                    this.jTextFieldName.setText("Enter Name..");
                    this.jComboBoxUserType.setSelectedIndex(0);
                    this.jComboBoxQuestions.setSelectedIndex(0);
                    this.jLabelRetype.setForeground(Color.black);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Password not match");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill required field");

    }//GEN-LAST:event_jButtonSaveActionPerformed
    }
    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed

        int user_cat_id = user_types_list.get(this.jComboBoxUserType.getSelectedIndex()).getUser_cat_id();
        int question_id = questions_list.get(this.jComboBoxQuestions.getSelectedIndex()).getQuestion_id();
        int user_selected_id = users_list.get(this.jTableUser.getSelectedRow()).getUser_id();
        String username = this.jTextFieldUsername.getText();
        String password = this.jTextFieldPassword.getText();
        String reTypePassword = this.jTextFieldRetypePassword.getText();
        String name = this.jTextFieldName.getText();
        String contact = this.jTextFieldContact.getText();
        String address = this.jTextFieldAddress.getText();
        String answer = this.jTextFieldAnswer.getText();

        if (!(username.equalsIgnoreCase("Enter Username...") || password.equalsIgnoreCase("Enter Password...")
                || reTypePassword.equalsIgnoreCase("Retype Password...")
                || name.equalsIgnoreCase("Enter Name..") || username.equalsIgnoreCase("") || password.equalsIgnoreCase("")
                || reTypePassword.equalsIgnoreCase("")
                || name.equalsIgnoreCase("") || name.equalsIgnoreCase(""))) {

            if (contact.equalsIgnoreCase("Enter Contact...")) {
                contact = "";
            }
            if (answer.equalsIgnoreCase("Enter Answer...")) {
                answer = "";
            }
            if (address.equalsIgnoreCase("Enter Address..")) {
                address = "";
            }

            if (reTypePassword.equals(password)) {
                int status = dbManager.modifyUser(
                        new User(user_selected_id, user_cat_id, question_id, 1, user_id, user_id, username, password, name,
                                address, CurrentDate.getCurrentDate(), contact, answer, CurrentDate.getCurrentDate()));
                this.jLabelRetype.setForeground(Color.black);

                if (status != 0) {
                    JOptionPane.showMessageDialog(this, "Successfully updated");
                    showInTable();
                    this.jTextFieldUsername.setText("Enter Username...");
                    this.jTextFieldPassword.setText("Enter Password...");
                    this.jTextFieldRetypePassword.setText("Retype Password...");
                    this.jTextFieldContact.setText("Enter Contact..");
                    this.jTextFieldAnswer.setText("Enter Answer...");
                    this.jTextFieldAddress.setText("Enter Address...");
                    this.jTextFieldName.setText("Enter Name..");
                    this.jComboBoxUserType.setSelectedIndex(0);
                    this.jComboBoxQuestions.setSelectedIndex(0);
                    this.jButtonUpdate.setVisible(false);
                    this.jButtonDelete.setVisible(false);
                    this.jButtonSave.setVisible(true);

                }
            } else {
                JOptionPane.showMessageDialog(this, "Password not match");
                this.jLabelRetype.setForeground(Color.red);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill required field");

        }


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        this.jTextFieldUsername.setText("Enter Username...");
        this.jTextFieldPassword.setText("Enter Password...");
        this.jTextFieldRetypePassword.setText("Retype Password...");
        this.jTextFieldContact.setText("Enter Contact..");
        this.jTextFieldAnswer.setText("Enter Answer...");
        this.jTextFieldAddress.setText("Enter Address...");
        this.jTextFieldName.setText("Enter Name..");
        this.jComboBoxUserType.setSelectedIndex(0);
        this.jComboBoxQuestions.setSelectedIndex(0);

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jTableUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableUserMouseClicked
        // TODO add your handling code here:
        this.jButtonUpdate.setVisible(true);
        this.jButtonDelete.setVisible(true);
        this.jButtonSave.setVisible(false);

        int user_type_id = users_list.get(this.jTableUser.getSelectedRow()).getUser_cat_id();
        int question_id = users_list.get(this.jTableUser.getSelectedRow()).getQuestion_id();

        this.jTextFieldUsername.setText(users_list.get(this.jTableUser.getSelectedRow()).getUser_name());
        this.jTextFieldPassword.setText(users_list.get(this.jTableUser.getSelectedRow()).getPassword());
        this.jTextFieldRetypePassword.setText("");
        this.jTextFieldContact.setText(users_list.get(this.jTableUser.getSelectedRow()).getContact_num());
        this.jTextFieldAnswer.setText(users_list.get(this.jTableUser.getSelectedRow()).getAnswer());
        this.jTextFieldAddress.setText(users_list.get(this.jTableUser.getSelectedRow()).getAddress());
        this.jTextFieldName.setText(users_list.get(this.jTableUser.getSelectedRow()).getName());
        this.jComboBoxUserType.setSelectedItem(dbManager.getUserType(user_type_id));
        this.jComboBoxQuestions.setSelectedItem(dbManager.getQuestion(question_id));

    }//GEN-LAST:event_jTableUserMouseClicked

    private void jTextFieldUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldUsernameMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldUsername.getText().equalsIgnoreCase("Enter Username...")) {
            this.jTextFieldUsername.setText("");
        }

    }//GEN-LAST:event_jTextFieldUsernameMouseClicked

    private void jTextFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsernameActionPerformed

    private void jTextFieldUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsernameKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldUsername.getText().equalsIgnoreCase("Enter Username...")) {
            this.jTextFieldUsername.setText("");
        }
    }//GEN-LAST:event_jTextFieldUsernameKeyPressed

    private void jTextFieldNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNameMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldName.getText().equalsIgnoreCase("Enter Name..")) {
            this.jTextFieldName.setText("");
        }
    }//GEN-LAST:event_jTextFieldNameMouseClicked

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNameActionPerformed

    private void jTextFieldNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNameKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldName.getText().equalsIgnoreCase("Enter Name..")) {
            this.jTextFieldName.setText("");
        }


    }//GEN-LAST:event_jTextFieldNameKeyPressed

    private void jTextFieldContactMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldContactMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldContact.getText().equalsIgnoreCase("Enter Contact...")) {
            this.jTextFieldContact.setText("");
        }
    }//GEN-LAST:event_jTextFieldContactMouseClicked

    private void jTextFieldContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldContactActionPerformed

    private void jTextFieldContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldContactKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldContact.getText().equalsIgnoreCase("Enter Contact...")) {
            this.jTextFieldContact.setText("");
        }
    }//GEN-LAST:event_jTextFieldContactKeyPressed

    private void jTextFieldAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAddressMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldAddress.getText().equalsIgnoreCase("Enter Address..")) {
            this.jTextFieldAddress.setText("");
        }
    }//GEN-LAST:event_jTextFieldAddressMouseClicked

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAddressKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldAddress.getText().equalsIgnoreCase("Enter Address..")) {
            this.jTextFieldAddress.setText("");
        }


    }//GEN-LAST:event_jTextFieldAddressKeyPressed

    private void jTextFieldAnswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAnswerMouseClicked
        // TODO add your handling code here:

        if (this.jTextFieldAnswer.getText().equalsIgnoreCase("Enter Answer...")) {
            this.jTextFieldAnswer.setText("");
        }

    }//GEN-LAST:event_jTextFieldAnswerMouseClicked

    private void jTextFieldAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnswerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnswerActionPerformed

    private void jTextFieldAnswerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAnswerKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldAnswer.getText().equalsIgnoreCase("Enter Answer...")) {
            this.jTextFieldAnswer.setText("");
        }
    }//GEN-LAST:event_jTextFieldAnswerKeyPressed

    private void jComboBoxQuestionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxQuestionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxQuestionsActionPerformed

    private void jComboBoxUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUserTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUserTypeActionPerformed

    private void jTextFieldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldPasswordMouseClicked
        if (this.jTextFieldPassword.getText().equalsIgnoreCase("Enter Password...")) {
            this.jTextFieldPassword.setText("");
        }
    }//GEN-LAST:event_jTextFieldPasswordMouseClicked

    private void jTextFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPasswordActionPerformed

    private void jTextFieldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPasswordKeyPressed
        if (this.jTextFieldPassword.getText().equalsIgnoreCase("Enter Password...")) {
            this.jTextFieldPassword.setText("");
        }

    }//GEN-LAST:event_jTextFieldPasswordKeyPressed

    private void jTextFieldRetypePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldRetypePasswordMouseClicked
        // TODO add your handling code here:
        if (this.jTextFieldRetypePassword.getText().equalsIgnoreCase("Retype Password...")) {
            this.jTextFieldRetypePassword.setText("");
        }
    }//GEN-LAST:event_jTextFieldRetypePasswordMouseClicked

    private void jTextFieldRetypePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRetypePasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRetypePasswordActionPerformed

    private void jTextFieldRetypePasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRetypePasswordKeyPressed
        // TODO add your handling code here:
        if (this.jTextFieldRetypePassword.getText().equalsIgnoreCase("Retype Password...")) {
            this.jTextFieldRetypePassword.setText("");
        }

    }//GEN-LAST:event_jTextFieldRetypePasswordKeyPressed

    private void jLabelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseClicked
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelExitMouseClicked

    private void jLabelMinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabelMinKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMinKeyPressed

    private void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
        this.setState(JFrame.ICONIFIED);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelMinMouseClicked

    private void jLabelExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseEntered
        this.jLabelExit.setBackground(Color.red);
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelExitMouseEntered

    private void jLabelExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExitMouseExited
        this.jLabelExit.setBackground(new Color(0, 0, 51));
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelExitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPage().setVisible(true);
            }
        });
    }

    public void showInUserTypesComboBox() {
        user_types_list = dbManager.getAllUserTypes();
        for (UserType userType : user_types_list) {

            this.jComboBoxUserType.addItem("" + userType.getUser_type());

        }
    }

    public void showInQuestionsComboBox() {
        questions_list = dbManager.getAllQuestions();
        for (Questions question : questions_list) {

            this.jComboBoxQuestions.addItem("" + question.getQuestions());

        }
    }

    public void showInTable() {
        tableModelCustomer.setRowCount(0);

        users_list = dbManager.getAllUsers();
        for (User user : users_list) {
            Vector V = new Vector();
            V.add(dbManager.getUserType(user.getUser_cat_id()));
            V.add(user.getUser_name());
            V.add(user.getName());
            V.add(user.getContact_num());
            V.add(user.getAddress());
            V.add(dbManager.getQuestion(user.getQuestion_id()));
            V.add(user.getAnswer());

            tableModelCustomer.addRow(V);
        }
    }

    public void checkPermissions(int user_cat_id) {
        ArrayList<Permissions> permissions_name_list;
        permissions_name_list = dbManager.getUserPermissionName(user_cat_id);

        for (Permissions permissions : permissions_name_list) {
            if ((permissions.getPermission_name().equalsIgnoreCase("Add User"))) {
                this.jButtonSave.setEnabled(true);
            } else if ((permissions.getPermission_name().equalsIgnoreCase("Update User"))) {
                this.jButtonUpdate.setEnabled(true);

            } else if ((permissions.getPermission_name().equalsIgnoreCase("Delete User"))) {
                this.jButtonDelete.setEnabled(true);

            }

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxQuestions;
    private javax.swing.JComboBox<String> jComboBoxUserType;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelExit;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelRetype;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldAnswer;
    private javax.swing.JTextField jTextFieldContact;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JPasswordField jTextFieldPassword;
    private javax.swing.JPasswordField jTextFieldRetypePassword;
    private javax.swing.JTextField jTextFieldUsername;
    // End of variables declaration//GEN-END:variables
}
